///////////////////////////////////////////////////////////////////////////////
// tb_audio_sdps.v : Unit test of sdp_engine against golden wire vectors
//
// Part of the DisplayPort_Verilog project.
//
// Drives the SDP engine with a known Maud, a known 4-sample buffer and a
// frame pulse, captures the SS...SE wire bytes of the three emitted
// packets (Audio_TimeStamp, Audio_Stream, Audio InfoFrame), and compares
// them byte-for-byte with vectors generated by misc/dp_sdp_golden.py
// (which is itself validated against the DP 1.1a spec test vectors).
//
// Compile with -DCFG_LANES=1 or 2 and -DVEC_DIR=path to the vector files.
///////////////////////////////////////////////////////////////////////////////
`timescale 1ns / 1ps

module tb_audio_sdps;

`ifndef CFG_LANES
 `define CFG_LANES 2
`endif

localparam LANE_COUNT  = `CFG_LANES;
localparam WB_PER_LANE = (LANE_COUNT == 1) ? 48 : 24;
localparam [8:0] SS = 9'b101011100;
localparam [8:0] SE = 9'b111111101;
localparam [8:0] DUMMY = 9'b000000011;

reg clk = 0;
always #5 clk = ~clk;

reg reset = 1;
reg [72:0] in_data = {1'b0, {4{DUMMY, DUMMY}}};
reg sdp_gap = 0, frame_pulse = 0;
reg [127:0] buffer;
reg buffer_ready = 0;
wire buffer_take, audio_mute;
wire [72:0] out_data;

sdp_engine #(
    .LANE_COUNT(LANE_COUNT), .AUDIO_BIT_WIDTH(16), .AUDIO_RATE(48000)
) dut (
    .clk(clk), .reset(reset),
    .in_data(in_data), .sdp_gap(sdp_gap), .frame_pulse(frame_pulse),
    .out_data(out_data),
    .buffer(buffer), .buffer_ready(buffer_ready), .buffer_take(buffer_take),
    .maud(24'd4971), .audio_mute(audio_mute)
);

always @(posedge clk)
    if (buffer_take) buffer_ready <= 0;

// ----------------------------------------------------------------------
// capture and compare one packet per lane
// ----------------------------------------------------------------------
integer errors = 0;

reg [8:0] cap0 [0:63];
reg [8:0] cap1 [0:63];
integer   ncap;

// capture SS + wire bytes + SE (fixed, known length)
task capture_fixed;
    integer c, cycles, guard;
    begin
        guard = 0;
        while (out_data[8:0] !== SS && guard < 5000) begin
            @(posedge clk); guard = guard + 1;
        end
        if (out_data[8:0] !== SS) begin
            $display("FAIL: no SS seen"); errors = errors + 1;
        end else begin
            cycles = (WB_PER_LANE + 2) / 2;
            ncap = 0;
            for (c = 0; c < cycles; c = c + 1) begin
                cap0[ncap]   = out_data[8:0];
                cap0[ncap+1] = out_data[17:9];
                cap1[ncap]   = out_data[26:18];
                cap1[ncap+1] = out_data[35:27];
                ncap = ncap + 2;
                @(posedge clk);
            end
        end
    end
endtask

integer f, i, v0, v1, r;

task compare_vec(input integer fh);
    begin
        f = fh;
        if (f == 0) begin
            $display("FAIL: cannot open vector file"); errors = errors + 1;
        end else begin
            if (cap0[0] !== SS) begin $display("FAIL: cap0[0] not SS"); errors = errors + 1; end
            if (LANE_COUNT == 2 && cap1[0] !== SS) begin $display("FAIL: cap1[0] not SS"); errors = errors + 1; end
            for (i = 0; i < WB_PER_LANE; i = i + 1) begin
                if (LANE_COUNT == 2)
                    r = $fscanf(f, "%h %h\n", v0, v1);
                else begin
                    r = $fscanf(f, "%h\n", v0); v1 = 0;
                end
                if (cap0[1+i] !== {1'b0, v0[7:0]}) begin
                    $display("FAIL: lane0 byte %0d got %03x want 0%02x", i, cap0[1+i], v0);
                    errors = errors + 1;
                end
                if (LANE_COUNT == 2 && cap1[1+i] !== {1'b0, v1[7:0]}) begin
                    $display("FAIL: lane1 byte %0d got %03x want 0%02x", i, cap1[1+i], v1);
                    errors = errors + 1;
                end
            end
            if (cap0[1+WB_PER_LANE] !== SE) begin
                $display("FAIL: lane0 SE missing (got %03x)", cap0[1+WB_PER_LANE]);
                errors = errors + 1;
            end
            if (LANE_COUNT == 2 && cap1[1+WB_PER_LANE] !== SE) begin
                $display("FAIL: lane1 SE missing"); errors = errors + 1;
            end
        end
    end
endtask

initial begin
    // 4 samples: {R,L} pairs, sample 0 in low bits
    buffer[ 31:  0] = {16'hABCD, 16'h1234};
    buffer[ 63: 32] = {16'hEF01, 16'h5678};
    buffer[ 95: 64] = {16'hFFFF, 16'h0000};
    buffer[127: 96] = {16'h7FFF, 16'h8000};

    repeat (5) @(posedge clk);
    reset <= 0;
    @(posedge clk);

    if (audio_mute !== 1'b1) begin
        $display("FAIL: audio_mute should start high"); errors = errors + 1;
    end

    // request all three packets (nonblocking so the DUT samples cleanly)
    frame_pulse <= 1; @(posedge clk); frame_pulse <= 0;
    buffer_ready <= 1;
    @(posedge clk); @(posedge clk);

    sdp_gap <= 1;
    @(posedge clk);

    // packet 1: timestamp
    capture_fixed;
    compare_vec($fopen(`VEC_TS, "r"));
    // packet 2: stream
    capture_fixed;
    compare_vec($fopen(`VEC_STREAM, "r"));
    // packet 3: infoframe
    capture_fixed;
    compare_vec($fopen(`VEC_INFO, "r"));

    repeat (4) @(posedge clk);
    if (audio_mute !== 1'b0) begin
        $display("FAIL: audio_mute should clear after ts+stream"); errors = errors + 1;
    end

    if (errors == 0)
        $display("ALL SDP VECTOR CHECKS PASSED (%0d-lane)", LANE_COUNT);
    else
        $display("%0d ERRORS (%0d-lane)", errors, LANE_COUNT);
    $finish;
end

endmodule
